<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Dotisan.Cli</AssemblyName>
    <RootNamespace>Dotisan.Cli</RootNamespace>
    <PackageId>Dotisan</PackageId>
    <ToolCommandName>dotisan</ToolCommandName>
    <PackAsTool>true</PackAsTool>
    <Version>0.8.6</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>dotnet;aspnetcore;scaffolding;cli;vue;typescript;openapi</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Description>Dotisan application scaffolding CLI.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dotisan.Core\Dotisan.Core.csproj" />
    <ProjectReference Include="..\Dotisan.Generators\Dotisan.Generators.csproj" />
    <ProjectReference Include="..\Dotisan.TypeScript\Dotisan.TypeScript.csproj" />
    <ProjectReference Include="..\Dotisan.OpenApi\Dotisan.OpenApi.csproj" />
    <None Include="..\..\README.md" Pack="true" PackagePath="README.md" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>
</Project>
