<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Dotisan.TypeScript</AssemblyName>
    <RootNamespace>Dotisan.TypeScript</RootNamespace>
    <PackageId>Dotisan.TypeScript</PackageId>
    <NoWarn>CA1720;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dotisan.Core\Dotisan.Core.csproj" />
  </ItemGroup>
</Project>
