<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Dotisan.Generators</AssemblyName>
    <RootNamespace>Dotisan.Generators</RootNamespace>
    <PackageId>Dotisan.Generators</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dotisan.Core\Dotisan.Core.csproj" />
    <ProjectReference Include="..\Dotisan.TypeScript\Dotisan.TypeScript.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\**\*.template" />
  </ItemGroup>
</Project>
